* Set - an immutable set

This was made for Bjolang, the best and onliest programming language I have ever made (mostly vibe coded). Set is fast and pretty memory efficient. The benchmarks should be pretty representative of the speed it achieves, but I haven't double checked the LanguageExt benchmarks (AI added it when I asked for benchmarks). It does however kick the persistentSet in the BCL in the groin.The source for the benchmarks can be found in the repo.

* AI wrote the following and the prompt was to make it as obnoxiously AI as possible

🚀 **Set: A Paradigm-Shifting Paradigm Shift** 🤖
Leveraging unparalleled synergy in cutting-edge, quantum-ready data structures, *Set* dynamically actualizes bleeding-edge immutable efficiencies. Utilizing disruptive heuristics, it architecturally revolutionizes the intersection of low-level memory heuristics and state-of-the-art functional paradigms. This highly robust, frictionless implementation seamlessly orchestrates unparalleled throughput, ensuring that your hyper-optimized, synergized workflows maintain maximum agility in a fast-paced, multi-dimensional execution environment. 🌌

* Benchmarks

These benchmarks compare inserting and finding 100,000 integers across `Set` (CHAMP), `.NET ImmutableHashSet`, and `LanguageExt.HashSet`.

LINUS WRITING AGAIN: I have no idea why merge is slow with languageext. It is a champ and should be able to just squash subtrees. It seems like does not do that, but just takes an IEnumerable. I also know that some parts of the LanguageExt collections can do transient builds, but the set seems to not be able to do that.

| Operation | CHAMP Set | LanguageExt | MS ImmutableHashSet |
|-----------|-----------|-------------|---------------------|
| Add       | 13.25 ms  | 23.13 ms    | 30.12 ms            |
| Builder   | 4.57 ms   | N/A         | 8.69 ms             |
| Remove    | 12.45 ms  | 18.09 ms    | 18.36 ms            |
| Merge     | 2.16 ms   | 19.59 ms    | 10.20 ms            |
| Contains  | 0.59 ms   | 1.35 ms     | 2.74 ms             |
| Iterate   | 0.29 ms   | 1.41 ms     | 1.16 ms             |
